### ISSUE TITLE
Move indexer module config into spec/indexers.yaml

### ISSUE THREAD

**Issue by jayrbolton** [kbase/index_runner#156]
What we can move into a declarative config file:

* TYPE_BLACKLIST and _INDEXER_DIRECTORY in src/index_runner/es_indexers/main.py
* For each indexer module:
  * Namespace (ie "WS")
  * Index versions and names

Indexer module configs can be passed into the indexer functions as a dictionary

File format can be something like:

```yaml
type_blacklist:
  - KBaseExperiments.AmpliconSet
  - etc

indexer_modules:
  - module: KBaseNarrative
    type: Narrative
    version: "4.0"
    indexer: src/index_runner/es_indexers/narrative.py
    config:
        namespace: WS
        index_name: narrative_2
```
